module.exports = {
  Potrace: {
    TURNPOLICY_BLACK: `NOT_USED`,
    TURNPOLICY_WHITE: `NOT_USED`,
    TURNPOLICY_LEFT: `NOT_USED`,
    TURNPOLICY_RIGHT: `NOT_USED`,
    TURNPOLICY_MINORITY: `NOT_USED`,
    TURNPOLICY_MAJORITY: `NOT_USED`,
  },
}
